# Bento’s BlueBook Price Guide
# Version 1.8

# Enchanted items pricing
# Enchanted items are priced based on their rarity, which is based on
# the probability of obtaining the enchantments when using an enchantment table
# 

# Set your server’s profit percentage. If 0%, then the recommended price will
# be exactly the cost of goods, no labor. 5% is a good value. 
profit: 5.0

# Set the value multiplier for enchantments. A value of 1.0 will result in an item
# doubling in price if it has a single, level I, common enchantment, like Bow Power I
enchantments: 1.0

# Currency symbol or name. If it is one character it will be prefixed, if it is a word, it will be suffixed.
# Examples
# currency: $
# currency: emeralds
# currency: coins
currency: $

# Text to show when quoting a price.
# If left as nothing, it will show the [Bluebook <version number>]
quote-text: '' 

#Set your default prices here. Commenting out a value will result in it becoming priceless and may make other items that use it priceless too.
#To set world-specific prices, add a section below this with just the price changes you want. They will overwrite these default prices.
block-prices:
   GRASS: 1
   DIRT: 0.5
   COBBLESTONE: 1
   SAPLING: 5
   SAND: 0.5
   GRAVEL: 0.5
   GOLD_ORE: 50
   IRON_ORE: 15
   COAL_ORE: 10
   LOG: 10
   LEAVES: 2
   LAPIS_ORE: 20
   WEB: 2.25
   WOOL: 5
   YELLOW_FLOWER: 1
   RED_ROSE: 1
   BROWN_MUSHROOM: 1
   RED_MUSHROOM: 1
   MOSSY_COBBLESTONE: 10
   OBSIDIAN: 50
   DIAMOND_ORE: 505
   REDSTONE_ORE: 15
   ICE: 7
   CACTUS: 5
   PUMPKIN: 10
   NETHERRACK: 5
   SOUL_SAND: 10
   HUGE_MUSHROOM_1: 2
   HUGE_MUSHROOM_2: 2
   VINE: 5
   MYCEL: 10
   WATER_LILY: 3
   ENDER_STONE: 10
   DRAGON_EGG: 1000
   EMERALD_ORE: 55
   QUARTZ_ORE: 20
   PACKED_ICE: 15
   APPLE: 3
   COAL: 8
   DIAMOND: 500
   STRING: 1.5
   FEATHER: 0.5
   SULPHUR: 10
   SEEDS: 1
   WHEAT: 3
   FLINT: 1
   PORK: 7.5
   WATER_BUCKET: 55
   LAVA_BUCKET: 128
   SADDLE: 100
   REDSTONE: 3
   SNOW_BALL: 1
   LEATHER: 10
   MILK_BUCKET: 55
   CLAY_BALL: 3
   SUGAR_CANE: 1
   SLIME_BALL: 10
   EGG: 0.5
   GLOWSTONE_DUST: 8
   RAW_FISH: 3
   INK_SACK: 3
   BONE: 5
   MELON: 1.5
   PUMPKIN_SEEDS: 15
   MELON_SEEDS: 15
   RAW_BEEF: 7.5
   RAW_CHICKEN: 5
   ROTTEN_FLESH: 1
   ENDER_PEARL: 50
   BLAZE_ROD: 100
   GHAST_TEAR: 75
   NETHER_STALK: 25
   SPIDER_EYE: 3
   EMERALD: 50
   CARROT_ITEM: 1
   POTATO_ITEM: 0.5
   POISONOUS_POTATO: 0.25
   NETHER_STAR: 250
   QUARTZ: 17.5
   IRON_BARDING: 120
   GOLD_BARDING: 350
   DIAMOND_BARDING: 3000
   NAME_TAG: 50
   GOLD_RECORD: 100
   GREEN_RECORD: 100
   RECORD_3: 100
   RECORD_4: 100
   RECORD_5: 100
   RECORD_6: 100
   RECORD_7: 100
   RECORD_8: 100
   RECORD_9: 100
   RECORD_10: 100
   RECORD_11: 100
   RECORD_12: 100
#  SPONGE: 10
   FIRE: 12
# COCOA PLANT, max 3 beans per plant
   COCOA: 15
# 1.7.2 Double plants
   DOUBLE_PLANT: 2
# 1.7. 2 New wood types
   LOG_2: 15
   LEAVES_2: 2

# World-specific prices should go here. You only need to list items that are specifc to the world. Crafted items will be calculated appropriately Format is:
# worldname:
#   material1: price
#   material2: price
# worldname2:
#   material4: price
# etc.

# Example - change to your own world
SkyWorld:
   GRASS: 1000
   DIRT: 500
