name: BlueBook
main: com.wasteofplastic.bluebook.BlueBook
version: 1.8
commands:
   bbreload:
      description: Reloads the BlueBook config
      usage: bluebook reload
      permission: bluebook.reload
      permission-message: You don't have <permission>
permissions:
   bluebook.show:
      description: Provides guide price for block or item when hitting a sign or chest.
      default: op
   bluebook.signshow:
      description: Displays object's value on any close by sign with [VALUE]
      default: op
